### ISSUE TITLE
How do I export for example my valorant sensitivity?

### ISSUE THREAD

**Issue by Verantor** [ahmadhayyan/project-aim#1]
How do I export for example my valorant sensitivity?

**Comment by ahmadhayyan** [comment]
Currently, the mouse sensitivity is similar to the one in Valorant.
Therefore, you can immediately use your Valorant sensitivity here.

**Comment by ahmadhayyan** [comment]
Currently, the mouse sensitivity is similar to the one in Valorant.
Therefore, you can immediately use your Valorant sensitivity here.

**Comment by ahmadhayyan** [comment]
Currently, the mouse sensitivity is similar to the one in Valorant.
Therefore, you can immediately use your Valorant sensitivity here.
